### ISSUE TITLE
Plan for layer 1/skateboard

### ISSUE THREAD

**Issue by paigejohnston** [paigejohnston/little-miss-naughty#1]
## Part A - Full gradient background

![laptop-screen](https://user-images.githubusercontent.com/53881641/64134622-b19cad80-ce33-11e9-93c9-832833d514eb.jpg)
![mobile-screen](https://user-images.githubusercontent.com/53881641/64134623-b5c8cb00-ce33-11e9-900a-6fc90f15122b.jpg)

- [ ] Purple = #663190
- [ ] Green = #009444
- [ ] Code for gradient
- [ ] Gradient to cover whole screen on laptop
- [ ] Gradient to cover whole screen on mobile

## Part B - Add Marquee down the side with text

![laptop-design-new](https://user-images.githubusercontent.com/53881641/64134673-4f907800-ce34-11e9-87d6-e4cf2a3f7380.jpg)
![mobile-design-new](https://user-images.githubusercontent.com/53881641/64134675-54edc280-ce34-11e9-854b-d4d2c6a58e4c.jpg)

**Comment by sehsarah** [comment]
Looks like you've achieved this so you can close/resolve this issue now. I'll close it
