### ISSUE TITLE
Gifs - Make flower gifs float/fall down the screen, accumulating at the bottom

### ISSUE THREAD

**Issue by paigejohnston** [paigejohnston/little-miss-naughty#5]
file:///Users/paigejohnston/Projects/paigejohnston/little-miss-naughty/index.html

Giffs- Not sure how to make it my giffs fall down the screen, I've looked at code pen codes but when I copy and paste it, it doesn't seem to work.
-Want to look at examples of code, that have something floating down the screen and see
how I can replace it, without messing it up by doing it incorrectly.
-Need to find code that will allow me to place a gif into and animation will be moving by
itself, floating down the screen, and potentially accumulating at the bottom of the screen.

**Comment by sehsarah** [comment]
I think that Zoey is using a falling motion in her truffula project so she could be a good person to talk to here https://github.com/zoeyyylim/truffula

**Comment by sehsarah** [comment]
I've also edited your Issue title to describe the particular issue you're solving

**Comment by paigejohnston** [comment]
Cool!! Thank-you heaps,  I'll message her. Not sure how to view her website?

**Comment by sehsarah** [comment]
It's a private repo so you will just need to talk to her about it

**Comment by paigejohnston** [comment]
yup! she said she's doing it in After Effects,  so I'll have a play around. 
Might also try use the cs annimation,  Elly showed us the week before last,  on Grace's site.

**Comment by sehsarah** [comment]
Ah yes, CSS animation would be cool for yours

**Comment by sehsarah** [comment]
Both of these use similar methods of CSS animation for falling leaves
https://codepen.io/uurrnn/pen/Kuylr
https://codepen.io/maiptn226/pen/Zvvdbq

You could analyse these and test out a similar method

Check with @ellysmlly if she likes this method or recommends something else

**Comment by ellysmlly** [comment]
Awesome yes! I think CSS animation is the best option for what you want to achieve @paigejohnston 

This example Sarah found should work perfectly
https://codepen.io/maiptn226/pen/Zvvdbq

If you want to have a go getting only 1 singular flower to fall, then I can explain `nth-child` used in this example to create different variations to the one falling animation

Looks fun!

**Comment by paigejohnston** [comment]
Elly helped me with key frames and flowers are now falling and giff is still rotating!
-Them accumulating at the bottom is something I can try find out for myself I can look on code pen for something,  if not- it's not a huge issue. Don't need it.
