### ISSUE TITLE
Screen extends height when (keyframed) flowers reach bottom of screen.

### ISSUE THREAD

**Issue by paigejohnston** [paigejohnston/little-miss-naughty#8]
file:///Users/paigejohnston/Projects/paigejohnston/little-miss-naughty/index.html
-Key frames in css:
@keyframes flower-falling {
  0% {
    top: -10vh;
  }

  100% {
    top: 210vh;
  }
}

-Screen size is 200%
-Screen extends to 210vh as key frame ends at 210vh,  so flowers come off the screen before restarting.
-Just want the screen height to stay 200%

**Comment by sehsarah** [comment]
@ellysmlly any tips for what Paige should look into here?

**Comment by paigejohnston** [comment]
key frames for flowers reached very bottom of page before resetting from the top of the screen,  I had to consider the size of the flower itself,  e.g one of the flowers was 5% and my screen height and end of the key frames was set at 200vh,  I altered the key frame to end at 195vh and the flower fell to the bottom of the screen (showing the entire flower) before disappearing and resetting.) Therefore,  the screen wasn't repeating at the very bottom.
